name: bukkit-discord-console
main: net.fxxstu.console.BukkitDiscordConsole
version: 1.0.0
author: Fxxst
description: External bukkit console!
api-version: 1.0.0
website: github.com/Fxxst-creator/bukkit-discord-console
